version: '3'
services:
  mariadb:
    image: mariadb:10.4-bionic
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mudar123
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: mudar123
    ports:
      - 3306:3306
    volumes:
     - ./data:/var/lib/mysql
